package digitalsoftware.com.destinasiwisata;

import java.util.ArrayList;

public class WisataData extends Wisata {
    public static String[][] data = new String[][]{
            {"(TRMS) Serulingmas", "terletak di kompleks Makam Ki Ageng Selamanik, di Lembah Sungai Serayu, kurang dari 1 kilo meter utara kota Banjarnegara. Sarana wisata yang ada di Taman Rekreasi Margasatawa Selamanik Seruling Mas antara lain : Taman satwa lengkap, kolam renang dengan waterboom-nya, Arena permainan anak, Panggung hiburan, Wisata arena pemancingan umum, juga terdapat Makam Ki Ageng Selomanik yang dikeramatkan.", "http://www.seputarbanjar.com/wp-content/uploads/2019/04/SATWA.jpg"},
            {"Candi Arjuna", "Candi Arjuna merupakan salah satu bangunan candi di Kompleks Percandian Arjuna, Dieng. Candi Arjuna diperkirakan sebagai candi tertua, candi ini diperkirakan dibangun pada abad 8 Masehi oleh Dinasti Sanjaya dari Mataram Kuno. Di kompleks ini juga terdapat Candi Semar, Candi Srikandi, Candi Puntadewa, dan Candi Sembadra. Candi Arjuna terletak paling utara dari deretan percandian di kompleks tersebut. Sementara itu, Candi Semar adalah candi perwara atau pelengkap dari Candi Arjuna. Kedua bangunan candi ini saling berhadapan.", "https://www.indonesiakaya.com/uploads/_images_gallery/cover/candi_arjuna_1290.jpg"},
            {"Waduk Mrica Banjarnegara", "Beralih dari kawasan Dieng. Dataran tinggi Dieng hanya satu dari sekian banyak wisata di banjarnegara jawa tengah. Masih banyak destinasi wisata di tempat lainnya. Waduk Mrica salah satunya. Di Waduk Mrica anda bisa menikmati hamparan permukaan air yang begitu luas. Kemudian jika anda ingin melihat danau buatan terbesar di Asia Tenggara, maka inilah danaunya. Waduk ini merupakan waduk yang membendung Sungai Serayu. Panorama alamnya tentu tak usah ditanya, anda bisa menikmati pesona alam disekitar waduk ini apalagi dengan berbagai fasilitas wisatanya. Wisata keluarga akan terasa nyaman di objek wisata Banjarnegara yang satu ini. Bisa dilakukan kegiatan menyenangkan seperti memancing, naik perahu, hingga main golf. Dan tahukah anda bahwa waduk ini merupakan salah satu pemasok listrik untuk Jawa dan Bali? Wah, kita yang mendapatkan pasokan listrik dari sini harus berterimakasih pada waduk Mrica ini.\n" +
                    "\n" +
                    "Lokasi : Desa Karangjambe, Kecamatan Wanadadi, Kabupaten Banjarnegara", "http://tempatwisataindonesia.id/wp-content/uploads/2016/08/Waduk-Mrica.png"},

            {"Surya Yudha Park Banjarnegara", "Berfoto di depan maskot Singapura dan Amerika secara bersamaan tanpa aplikasi edit foto hanya bisa dilakukan di tempat yang satu ini. Surya Yudha Park memiliki patung Merlion dan patung Liberty yang berdiri bersebelahan. Belum memiliki kesempatan ke dua negara maju tersebut maka bisa terlebih dahulu mengunjungi Surya Yudha Park. Tempat wisata yang satu ini merupakan sebuah taman rekreasi air yang paling lengkap di Banjarnegara. Tempat wisata di Banjarnegara ini mengusung konsep wisata terpadu dengan berbagai kelengkapan fasilitas seperti hotel berbintang, arena olahraga, rafting, juga wisata outbound. Merupakan salah satu alternatif wisata keluarga yang menarik.\n" +
                    "\n" +
                    "Lokasi : Jl. Raya Karang Kobar KM. 1, Desa Rejasa, Kecamatan Madukara, Kabupaten Banjarnegara", "http://tempatwisataindonesia.id/wp-content/uploads/2016/08/Surya-Yudha-Park.png"},
            {"Arum Jeram Sungai Serayu", "Selain berkaitan dengan Tampo Mas, Waduk Mrica juga berkaitan dengan Sungai Serayu. Tentu Sungai Serayu sudah tak asing lagi di telinga masyarakat Banjarnegara. Apalagi dengan wisata raftingnya yang semakin berkembang. Terkenal kemana-mana menarik perhatian para wisatawan yang menyukai wisata air dan uji adrenalin. Terutama bagi anda yang menyukai tantangan, belum lengkap jika belum mencoba uji adrenalin di Sungai Serayu. Objek wisata Banjarnegara rafting Sungai Serayu begitu menarik karena sembari menikmati lika-liku Sungai Serayu anda juga disuguhi pemandangan alam nan eksotis.\n" +
                    "\n" +
                    "Lokasi Desa : Desa Singamerta, Kecamatan Sigaluh, Kabupaten Banjarnegara", "http://tempatwisataindonesia.id/wp-content/uploads/2016/08/Rafting-Sungai-Serayu.png"},
            {"Wadas Tumpang Banjarnegara", "Ke Banjarnegara selain menikmati wisata alam, kita juga bisa berwisata budaya. Masih banyak daerah di Indonesia yang masih kental dengan adat budayanya juga berbagai ritualnya meski sudah memasuki era modern. Berbagai kebiasaan adat istiadat tersebut memang menjadi kekayaan tersendiri bagi bangsa Indonesia. Wadas Tumpang menjadi salah satu tempat wisata Banjarnegara yang menunjukkan kekentalan budaya tersebut. Dulu tempat ini terkenal sebagai tempat pertapaan masyarakat Banjarnegara dan sekitarnya. Dibuktikan dengan sesaji yang ada disana. Wadas Tumpang menjadi tempat yang digandrungi wisatawan pasalnya selain menarik dengan sisi mistisnya, tempat ini juga memiliki pemandangan indah dan udara sejuk khas dataran tinggi. Anda juga bisa melihat kandang macan alami dari akar pohon dan kera putih berseliweran. Gunung tumpukan dua batu yang diselimuti pohon beringin besar ratusan tahun ini sangat menarik untuk dikunjungi.\n" +
                    "\n" +
                    "Lokasi : Desa Majalengka, Kecamatan Bawang, Kabupaten Banjarnegara", "http://tempatwisataindonesia.id/wp-content/uploads/2016/08/Wadas-Tumpang.png"},

            {"Dataran Tinggi Dieng (Dieng Plateu)", "Dataran Tinggi Dieng (Dieng Plateu) terletak disebelah timur laut Kota Banjarnegara 55km, merupakan daerah tujuan wisata nomor 2 di Jawa Tengah setelah Borobudur.\n" +
                    "Dataran Tinggi Dieng semula merupakan Gunung Berapi yang meletus dengan dahsyat, sekarang puncak gunung terlempar, tinggallah sekarang suatu dataran yang terletak di puncak gunung lebih dikenal dengan sebutan \" DIENG PLATEU\".", "https://banjarnegarakab.go.id/v3/images/stories/dieng2%20-%20ok.jpg"},
            {"Candi Arjuna", "Candi Arjuna merupakan salah satu bangunan candi di Kompleks Percandian Arjuna, Dieng. Candi Arjuna diperkirakan sebagai candi tertua, candi ini diperkirakan dibangun pada abad 8 Masehi oleh Dinasti Sanjaya dari Mataram Kuno. Di kompleks ini juga terdapat Candi Semar, Candi Srikandi, Candi Puntadewa, dan Candi Sembadra. Candi Arjuna terletak paling utara dari deretan percandian di kompleks tersebut. Sementara itu, Candi Semar adalah candi perwara atau pelengkap dari Candi Arjuna. Kedua bangunan candi ini saling berhadapan.", "https://www.indonesiakaya.com/uploads/_images_gallery/cover/candi_arjuna_1290.jpg"},
            {"Anglir Mendung Banjarnegara","Anglir Mendung merupakan tempat wisata di Banjar yang memiliki udara sejuk karena dikelilingi oleh Hutan Lindung. Di tempat ini terapat fasilitas kolam renang dan taman untuk anak-anak bermain. Selain itu, kalau anda mau melakukan kegiatan diluar ruangan, lokasi isi cocok untuk bumi perkemahan dengan kapasitas 200 tenda.","http://tempatwisataindonesia.id/wp-content/uploads/2016/08/Anglir-Mendung.png"},
            {"(TRMS) Serulingmas", "terletak di kompleks Makam Ki Ageng Selamanik, di Lembah Sungai Serayu, kurang dari 1 kilo meter utara kota Banjarnegara. Sarana wisata yang ada di Taman Rekreasi Margasatawa Selamanik Seruling Mas antara lain : Taman satwa lengkap, kolam renang dengan waterboom-nya, Arena permainan anak, Panggung hiburan, Wisata arena pemancingan umum, juga terdapat Makam Ki Ageng Selomanik yang dikeramatkan.", "http://www.seputarbanjar.com/wp-content/uploads/2019/04/SATWA.jpg"},
            {"Candi Arjuna", "Candi Arjuna merupakan salah satu bangunan candi di Kompleks Percandian Arjuna, Dieng. Candi Arjuna diperkirakan sebagai candi tertua, candi ini diperkirakan dibangun pada abad 8 Masehi oleh Dinasti Sanjaya dari Mataram Kuno. Di kompleks ini juga terdapat Candi Semar, Candi Srikandi, Candi Puntadewa, dan Candi Sembadra. Candi Arjuna terletak paling utara dari deretan percandian di kompleks tersebut. Sementara itu, Candi Semar adalah candi perwara atau pelengkap dari Candi Arjuna. Kedua bangunan candi ini saling berhadapan.", "https://www.indonesiakaya.com/uploads/_images_gallery/cover/candi_arjuna_1290.jpg"},
            {"(TRMS) Serulingmas", "terletak di kompleks Makam Ki Ageng Selamanik, di Lembah Sungai Serayu, kurang dari 1 kilo meter utara kota Banjarnegara. Sarana wisata yang ada di Taman Rekreasi Margasatawa Selamanik Seruling Mas antara lain : Taman satwa lengkap, kolam renang dengan waterboom-nya, Arena permainan anak, Panggung hiburan, Wisata arena pemancingan umum, juga terdapat Makam Ki Ageng Selomanik yang dikeramatkan.", "http://www.seputarbanjar.com/wp-content/uploads/2019/04/SATWA.jpg"},
            {"Candi Arjuna", "Candi Arjuna merupakan salah satu bangunan candi di Kompleks Percandian Arjuna, Dieng. Candi Arjuna diperkirakan sebagai candi tertua, candi ini diperkirakan dibangun pada abad 8 Masehi oleh Dinasti Sanjaya dari Mataram Kuno. Di kompleks ini juga terdapat Candi Semar, Candi Srikandi, Candi Puntadewa, dan Candi Sembadra. Candi Arjuna terletak paling utara dari deretan percandian di kompleks tersebut. Sementara itu, Candi Semar adalah candi perwara atau pelengkap dari Candi Arjuna. Kedua bangunan candi ini saling berhadapan.", "https://www.indonesiakaya.com/uploads/_images_gallery/cover/candi_arjuna_1290.jpg"},
            {"(TRMS) Serulingmas", "terletak di kompleks Makam Ki Ageng Selamanik, di Lembah Sungai Serayu, kurang dari 1 kilo meter utara kota Banjarnegara. Sarana wisata yang ada di Taman Rekreasi Margasatawa Selamanik Seruling Mas antara lain : Taman satwa lengkap, kolam renang dengan waterboom-nya, Arena permainan anak, Panggung hiburan, Wisata arena pemancingan umum, juga terdapat Makam Ki Ageng Selomanik yang dikeramatkan.", "http://www.seputarbanjar.com/wp-content/uploads/2019/04/SATWA.jpg"},
            {"Candi Arjuna", "Candi Arjuna merupakan salah satu bangunan candi di Kompleks Percandian Arjuna, Dieng. Candi Arjuna diperkirakan sebagai candi tertua, candi ini diperkirakan dibangun pada abad 8 Masehi oleh Dinasti Sanjaya dari Mataram Kuno. Di kompleks ini juga terdapat Candi Semar, Candi Srikandi, Candi Puntadewa, dan Candi Sembadra. Candi Arjuna terletak paling utara dari deretan percandian di kompleks tersebut. Sementara itu, Candi Semar adalah candi perwara atau pelengkap dari Candi Arjuna. Kedua bangunan candi ini saling berhadapan.", "https://www.indonesiakaya.com/uploads/_images_gallery/cover/candi_arjuna_1290.jpg"},
            {"Pemandian Air Hangat Pingit", "Desa Gumelem, khususnya Gumelem Wetan dengan wilayah yang cukup luas dan jumlah penduduk yang cukup banyak merupakan daerah peninggalan jaman kademangan dimana banyak peninggalan-peninggalan yang bersifat sejarah baik itu tempat, seni dan budaya, maupun adat-istiadatnya.\n" +
                    "\n" +
                    "Terdapat beberapa tempat di Desa Gumelem Wetan yang dapat dijadikan sebagai obyek wisata.  Salah satu diantaranya adalah tempat pemandian air hangat ” Pingit “.\n" +
                    "\n" +
                    "Pemandian air hangat “Pingit” merupakan pemandian yang bersumber pada mata air panas yang berasal dari pegunungan yang ada di Desa Gumelem Wetan, sehingga air panas ini mengandung belerang.  Kandungan belerang yang terdapat di dalam air ini mempunyai khasiat salah satunya dapat mengobati penyakit kulit.  Banyak orang mendatangi pemandian air hangat “Pingit” ini dengan berbagai tujuan.  Ada yang datang hanya sekedar berkunjung untuk menikmati wisata alam sepanjang jalan menuju lokasi, ada juga yang berkunjung karena ingin mengobati penyakit kulit yang dideritanya dengan cara mandi di pemandian tersebut.\n", "https://purwokertokita.com/wp-content/uploads/2018/07/WhatsApp-Image-2018-07-26-at-15.10.50-768x512.jpeg"},
            {"Kawah Sikidang Dieng", "Kawah Sikidang Dieng Plateau - Kawah Sikidang Dieng serupakan salah satu spot yang menjadi tujuan utama bila kita berwiisata ke kawasan dataran tinggi Dieng. Kawah Sikidang  sendiri terbentuk dari letusan gunung berapi pada jaman dahulu, yang menarik Kawah Sikidang ini masih aktif sampai sekarang namun masuk dalam kategori aman untuk dikunjungi karena kadar belerang yang rendah. Tak ayal keunikan ini lah yang menarik perhatian wisatawan untuk berkunjung dan melepas lelah dengan menikmati keindahan alam Kawah Sikidang Dieng.\nKawah Sikidang Dieng memiliki keunikan yang mungkin tidak bisa didapatkan di tempat lain, disamping suasana alam yang indah, kabut kabut yang eksotis menambah sensasi wisata alam yang sedikit berbeda. Ya berbeda karena kawah ini masih aaktif samapai sekarang dengan fluktuasi keaktifan yang beragam namun dalam skala rendah, aroma belerang pun tidak terlalu menyengat sehingga Kawah Sikidang Dieng ini aman untuk dikunjungi. So jangan lewatkan kesempatan untuk sekedar berfoto selfie rua di kawasan indah Kawah Sikidang Dieng ini. \nSeperti halnya objek wisata lainya di Indonesia Kawah Sikidang Dieng juga memiliki legenda yang kental dengan cerita rakyat atau mitos mitos jaman dahulu. Konon ceritanya pada jaman dahulu di kawasan dataran tinggi dieng ini terdapat sebuah istana yang dimiliki oleh seorang  ratu cantik jelita bernama Ratu Shinta Dewi. Karena kecantikan ini juga yang membuat Ratu Shinta Dewi menjadi pujaan dan rebutan banyak pangeran dan raja raja pada zaman itu. Suatu ketika datanglah seorang pangeran bernama Pangeran Kidang Garungan, tidak seperti pangeran pangeran pada umumnya pangeran Kidang Garungan berpenampilan aneh yaitu berbadan manusia namun berkepala kidang atau Kijang yang ditempat lain mungkin disebut rusa. Melihat kondisi fisik pangeran Kidang Garungan ini membuat sang ratu bingung. Akirnya Ratu Shinta Dewi memberikan satu syarat kepada sang pangeran apa bila ingin meminang nya. Syarat nya adalah sang pangeran harus membuat sumur yang besar dan dalam di kawasan Dieng seorang diri. Mendengar syarat dari sang ratu itu Pangeran Kidang Garungan pun menyanggupinya.\nhttp://caritujuanwisata.blogspot.com/2015/10/kawah-sikidang-dieng.html", "http://1.bp.blogspot.com/-is9jHs0XTJQ/VhmdVShSajI/AAAAAAAAAJo/3C4gmwGno28/s1600/kawah%2Bsikidang%2Bbibir%2Bkawah.png"},
    };

    public static ArrayList<Wisata> getListData() {
        ArrayList<Wisata> list = new ArrayList<>();
        for (String[] aData : data) {
            Wisata wisata = new Wisata();
            wisata.setName(aData[0]);
            wisata.setDeskripsi(aData[1]);
            wisata.setPhoto(aData[2]);

            list.add(wisata);
        }
        return list;
    }
}
